/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionStyle: typeof import('./components/AccordionStyle.vue')['default']
    ClassicalStyle: typeof import('./components/ClassicalStyle.vue')['default']
    ControlsPannel: typeof import('./components/ControlsPannel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconAbout: typeof import('./components/icons/IconAbout.vue')['default']
    IconDevice: typeof import('./components/icons/IconDevice.vue')['default']
    IconMusicNext: typeof import('./components/icons/IconMusicNext.vue')['default']
    IconMusicPause: typeof import('./components/icons/IconMusicPause.vue')['default']
    IconMusicPlay: typeof import('./components/icons/IconMusicPlay.vue')['default']
    IconMusicPrev: typeof import('./components/icons/IconMusicPrev.vue')['default']
    IconPlay: typeof import('./components/icons/IconPlay.vue')['default']
    IconRandom: typeof import('./components/icons/IconRandom.vue')['default']
    IconRepeatAll: typeof import('./components/icons/IconRepeatAll.vue')['default']
    IconRepeatOne: typeof import('./components/icons/IconRepeatOne.vue')['default']
    IconStar: typeof import('./components/icons/IconStar.vue')['default']
    IconToFullscreen: typeof import('./components/icons/IconToFullscreen.vue')['default']
    IconToWindow: typeof import('./components/icons/IconToWindow.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
